substitutions:
  name: garage-door
  friendly_name: Garage Door
  upper_devicename: "ESP32 4 relay and 1 sensor "
  project_name: "Taiwan Smart Home Technology.Garage Door"
  project_version: "1.0" 
  wifi_signal_update_interval: "600s"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: "${project_name}"
    version: "${project_version}"
  comment: ${upper_devicename}   
  name_add_mac_suffix: False

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG
  baud_rate: 0

api:

ota:
  - platform: esphome

status_led:
  pin: GPIO2

web_server:
  port: 80
  version: 3

##  WIFI  ##########################
wifi:
  # Set up a wifi access point
  ap: {}
captive_portal:
############################3333333


## LAN ##########################
# ethernet:
#   type: W5500
#   clk_pin: GPIO18
#   mosi_pin: GPIO23
#   miso_pin: GPIO19
#   cs_pin: GPIO5
#   interrupt_pin: GPIO14
#   #reset_pin: GPIO25
#   clock_speed: 40Mhz
################################


text_sensor:

### LAN  ################################
  # - platform: ethernet_info
  #   ip_address:
  #     name: IP Address
  #     icon: mdi:ip-network  

## Wifi ################################     
  - platform: wifi_info
    ip_address:
      name: "IP"      
      icon: "mdi:ip-outline"
    ssid:
      name: "SSID"
      icon: "mdi:router-wireless"
    mac_address:
      name: "MAC"
      icon: "mdi:lan"
## Wifi ################################  
sensor:
  - platform: wifi_signal
    name: "Signal"
    update_interval: 600s  
    icon: mdi:signal


switch:
  - platform: gpio
    name: Up
    pin:
      number: GPIO25
      inverted: false
    id: relay_up
    icon: mdi:menu-up
    restore_mode: ALWAYS_OFF 
    # internal: true 
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay_up

  - platform: gpio
    name: Down
    pin:
      number: GPIO27
      inverted: false
    id: relay_down
    icon: mdi:menu-down
    restore_mode: ALWAYS_OFF 
    # internal: true 
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay_down

  - platform: gpio
    name: Stop
    pin:
      number: GPIO26
      inverted: false
    id: relay_stop
    icon: mdi:stop
    restore_mode: ALWAYS_OFF 
    # internal: true 
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay_stop

  - platform: gpio
    name: Other
    pin:
      number: GPIO22
      inverted: false
    id: relay_other
    icon: mdi:dots-horizontal
    restore_mode: ALWAYS_OFF 
    internal: true 
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay_other

  - platform: template
    name: "Gig door Switch"
    lambda: |-
      if (id(reed_door_sensor).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: relay_up
    turn_off_action:
      - switch.turn_on: relay_down
button:
  - platform: restart
    name: "Restart"
    entity_category: "diagnostic"
    icon: mdi:restart

binary_sensor:
  - platform: gpio
    name: Ground Sensor
    icon: mdi:doorbell-video
    pin: 
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    id: reed_door_sensor
    # internal: true    

cover:
  - platform: template
    device_class: garage
    name: My Garage Door
    id: template_cover1
    lambda: |-
      if (id(reed_door_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: relay_up
    close_action:
      - switch.turn_on: relay_down
    stop_action:
      - switch.turn_on: relay_stop
