substitutions:
  name: "garage-door-iii-b2a890"
  friendly_name: Garage Door III b2a890
  upper_devicename: "ESP32 3 relay and 3 sensor "
  project_name: "Taiwan Smart Home Technology.Garage Door"
  project_version: "2025.4" 
  wifi_signal_update_interval: "600s"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: "${project_name}"
    version: "${project_version}"
  comment: ${upper_devicename}   
  name_add_mac_suffix: False

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

light:
  - platform: status_led
    name: "Status LED OFF"
    id: green_led_off
    pin: 2
    entity_category: config
    disabled_by_default: False
    restore_mode: RESTORE_DEFAULT_OFF     

web_server:
  port: 80

##  WIFI  ##########################
wifi:
  # Set up a wifi access point
  ap: {}
captive_portal:
############################3333333
## LAN ##########################
# ethernet:
#   type: W5500
#   clk_pin: GPIO18
#   mosi_pin: GPIO23
#   miso_pin: GPIO19
#   cs_pin: GPIO5
#   interrupt_pin: GPIO4
  #reset_pin: GPIO25
#   clock_speed: 40Mhz
##############################
text_sensor:
### LAN  ################################
  # - platform: ethernet_info
  #   ip_address:
  #     name: IP Address
  #     icon: mdi:ip-network  

## Wifi ################################     
  - platform: wifi_info
    ip_address:
      name: "IP"      
      icon: "mdi:ip-outline"
    ssid:
      name: "SSID"
      icon: "mdi:router-wireless"
    mac_address:
      name: "MAC"
      icon: "mdi:lan"
## Wifi ################################  
sensor:
  - platform: wifi_signal
    name: "Signal"
    update_interval: 600s  
    icon: mdi:signal


switch:
  - platform: gpio
    name: UP_22
    pin:
      number: GPIO22
      inverted: True
      # mode: INPUT_PULLUP  
    id: relay_up
    icon: mdi:menu-up-outline
    restore_mode: ALWAYS_OFF 
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay_up


  - platform: gpio
    name: DOWN_27
    pin:
      number: GPIO27
      inverted: True
      # mode: INPUT_PULLUP  
    id: relay_down
    icon: mdi:menu-down-outline
    restore_mode: ALWAYS_OFF   
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay_down


  - platform: gpio
    name: STOP_26
    pin:
      number: GPIO26
      inverted: True
      # mode: INPUT_PULLUP  
    id: relay_stop
    icon: mdi:stop
    restore_mode: ALWAYS_OFF     
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay_stop   

  - platform: gpio
    name: LASER_POWER_SWITCH
    pin:
      number: GPIO25
      inverted: True
      # mode: INPUT_PULLUP  
    id: laser_power_switch
    icon: mdi:laser-pointer
    restore_mode: ALWAYS_OFF 


binary_sensor:
  - platform: gpio
    id: door_sensor
    name: "Door Sensor"
    pin:
      number: 33
      # inverted: true
      mode: INPUT_PULLUP     

  - platform: gpio
    id: button_sensor
    name: "Button Sensor"
    pin:
      number: 15
      inverted: true
      mode: INPUT_PULLUP            

  - platform: gpio
    id: laser_sensor_1
    name: "Laser Sensor 1"
    pin:
      number: 14
      inverted: true
      mode: INPUT_PULLUP     

  - platform: gpio
    id: laser_sensor_2
    name: "Laser Sensor 2"
    pin:
      number: 12
      inverted: true
      mode: INPUT_PULLUP                 
      
cover:
  - platform: template
    device_class: garage
    name: "Garage"
    id: template_cover1
    lambda: |-
      if (id(door_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: relay_up
    close_action:
      - switch.turn_on: relay_down
    stop_action:
      - switch.turn_on: relay_stop      
