substitutions:
  name: "two-way-wifi-a82118"
  friendly_name: Two Way Wifi a82118

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev
  on_boot: 
    then:
      - if:
          condition:
            - lambda: 'return id(default_relay1_state).state == "OFF" ;'
          then:
            - switch.turn_off: relay_1
      - if:
          condition:
            - lambda: 'return id(default_relay1_state).state == "ON" ;'
          then:
            - switch.turn_on: relay_1      
      - if:
          condition:
            - lambda: 'return id(default_relay2_state).state == "OFF" ;'
          then:
            - switch.turn_off: relay_2  
      - if:            
          condition:
            - lambda: 'return id(default_relay2_state).state == "ON" ;'
          then:
            - switch.turn_on: relay_2    
select:
  - platform: template
    name: "Default Relay1 State"
    id: default_relay1_state
    optimistic: True
    restore_value:  True
    options: 
      - "ON"
      - "OFF"
    initial_option: "OFF"

  - platform: template
    name: "Default Relay2 State"
    id: default_relay2_state
    optimistic: True
    restore_value:  True
    options: 
      - "ON"
      - "OFF"
    initial_option: "OFF"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s  #取消當持續15分鐘找不網路時重置系統。
# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:
  port: 80
  version: 3

switch:
  - platform: gpio
    id: relay_1
    pin: GPIO02
    name: "Relay_1"
    icon: mdi:electric-switch

  - platform: gpio
    id: relay_2
    pin: GPIO04
    name: "Relay_2"
    icon: mdi:electric-switch

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"      
      icon: "mdi:ip-outline"
    ssid:
      name: "SSID"
      icon: "mdi:router-wireless"
    mac_address:
      name: "MAC"
      icon: "mdi:lan"
