substitutions:
  name: "ble-tracker-proxy-73a3f0"
  friendly_name: Ble Tracker Proxy 73a3f0

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: "jeremy_2.4G"
  password: "J2iduxdgr"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: ""

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32c3.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:
  port: 80
  version: 3

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true  

light:
  - platform: neopixelbus
    type: GRB
    variant: ws2812
    pin: GPIO8
    num_leds: 1
    name: "ble-tracker-proxy-73a3f0"       
    icon: mdi:led-on     
