substitutions:
  name: "aircube-plus"
  friendly_name: AirCube Plus
  upper_devicename: "ESP32S CM1106 PM2105 HDC1080 SGFP30 TTL223"
  project_name: "Taiwan Smart Home Technology.DAIKIN Air Cube Plus"
  project_version: "2.0" 
  temperature_offset: "0"
  humidity_offset: "0"  
  temperature_update_interval: "6s"
  wifi_signal_update_interval: "600s"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: "${project_name}"
    version: "${project_version}"
  comment: ${upper_devicename}    
  name_add_mac_suffix: True

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ap: {}

api:
  reboot_timeout: 0s
  
ota:
  - platform: esphome
    id: ota_esphome
  - platform: web_server
    id: web_server_managed

captive_portal:

web_server:
  port: 80
  version: 3

logger:
  logs:
    hdc1080: WARN
    sgp30: WARN
    sensor: WARN
    component: ERROR

uart:
- id: cm1106_uart
  rx_pin: 16
  tx_pin: 17
  baud_rate: 9600

i2c:
  - id: pm25_bus
    sda: 23
    scl: 22
    scan: true
  - id: th_bus
    sda: 19
    scl: 21
    scan: true
    
sensor:
# UPTIME SENSOR
  - platform: uptime
    name: Uptime  

# CO2 SENSOR

  - platform: cm1106
    uart_id: cm1106_uart
    id: co2sensor_cm1106
    update_interval: ${temperature_update_interval}
    co2:
      name: "CO2"
      icon: mdi:molecule-co2
      id: co2sensor
      device_class: carbon_dioxide
      state_class: measurement
      unit_of_measurement: "ppm"

# PM2.5 SENSOR 
  - platform: pm2005
    i2c_id: pm25_bus
    type: pm2005
    id: pm25_pm20x5
    update_interval: ${temperature_update_interval}
    pm_2_5: 
      name: "PM2.5"
      icon: mdi:molecule
      id: pm25sensor
      device_class: pm25
      state_class: measurement
      unit_of_measurement: "µg/m³"
      filters:
        - lambda: "return std::max(0.0f, x - 4);"
    pm_1_0:
      name: "PM1.0"  
      internal: true  
      id: pm10sensor            
# TVOC SENSOR
  - platform: sgp30
    i2c_id: th_bus
    update_interval: ${temperature_update_interval}
    compensation:
      temperature_source: temperature
      humidity_source: humidity
    eco2:
      id: eco2sensor
      internal: true
    tvoc:
      name: "TVOC"
      id: tvocsensor
      device_class: volatile_organic_compounds
      unit_of_measurement: "ppb"      
      filters:
        - throttle: 15s
        - lambda: "return x + id(tvoc_offset_ui).state;"

# TEMPERATURE AND HUMIDITY SENSOR
  - platform: hdc1080
    i2c_id: th_bus
    update_interval: ${temperature_update_interval}
    temperature:
      name: "Temperature"
      icon: mdi:thermometer
      id: temperature
      accuracy_decimals: 1
      filters:
        - offset: ${temperature_offset}
        - lambda: "return x + id(temperature_offset_ui).state;"          
    humidity:
      name: "Humidity"
      icon: mdi:water-percent
      accuracy_decimals: 1
      id: humidity
      filters:
        - offset: ${humidity_offset}
        - lambda: "return x + id(humidity_offset_ui).state;"    

# FOR WIFI SIGNAL
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: ${wifi_signal_update_interval}
    internal: true
    entity_category: "diagnostic"

  - platform: copy
    source_id: wifi_signal_db
    icon: mdi:signal
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"


  - platform: aqi
    name: "Air Quality Index"
    pm_2_5: pm25sensor
    pm_10_0: pm10sensor
    calculation_type: AQI

# AQI INDEX SENSOR
  - platform: copy
    source_id: pm25sensor
    id: pm_2_5
    internal: true
    accuracy_decimals: 0
    filters:
    - sliding_window_moving_average:
        window_size: 5
        send_every: 10
    - throttle_average: 60s
    - delta: 10        
    on_value:
      lambda: |-
        // https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
        if (id(pm_2_5).state < 12.0) {
          // good
          id(aqi_text).publish_state("good");
          id(aqi_color).publish_state("green");
          id(pm_2_5_aqi).publish_state((50.0 - 0.0) / (12.0 - 0.0) * (id(pm_2_5).state - 0.0) + 0.0);
        } else if (id(pm_2_5).state < 35.4) {
          // moderate
          id(aqi_text).publish_state("moderate");
          id(aqi_color).publish_state("yellow");
          id(pm_2_5_aqi).publish_state((100.0 - 51.0) / (35.4 - 12.1) * (id(pm_2_5).state - 12.1) + 51.0);
        } else if (id(pm_2_5).state < 55.4) {
          // Unhealthy for Sensitive Groups
          id(aqi_text).publish_state("unhealthy for sensitive groups");
          id(aqi_color).publish_state("orange");
          id(pm_2_5_aqi).publish_state((150.0 - 101.0) / (55.4 - 35.5) * (id(pm_2_5).state - 35.5) + 101.0);
        } else if (id(pm_2_5).state < 150.4) {
          // unhealthy
          id(aqi_text).publish_state("unhealthy");
          id(aqi_color).publish_state("red");
          id(pm_2_5_aqi).publish_state((200.0 - 151.0) / (150.4 - 55.5) * (id(pm_2_5).state - 55.5) + 151.0);
        } else if (id(pm_2_5).state < 250.4) {
          // very unhealthy
          id(aqi_text).publish_state("very unhealthy");
          id(aqi_color).publish_state("purple");
          id(pm_2_5_aqi).publish_state((300.0 - 201.0) / (250.4 - 150.5) * (id(pm_2_5).state - 150.5) + 201.0);
        } else if (id(pm_2_5).state < 350.4) {
          // hazardous
          id(aqi_text).publish_state("hazardous");
          id(aqi_color).publish_state("brown");
          id(pm_2_5_aqi).publish_state((400.0 - 301.0) / (350.4 - 250.5) * (id(pm_2_5).state - 250.5) + 301.0);
        } else if (id(pm_2_5).state < 500.4) {
          // hazardous 2
          id(aqi_text).publish_state("hazardous");
          id(aqi_color).publish_state("brown");
          id(pm_2_5_aqi).publish_state((500.0 - 401.0) / (500.4 - 350.5) * (id(pm_2_5).state - 350.5) + 401.0);
        }        

# AQI RANGE SENSOR
  - platform: template
    name: "AQI range"
    icon: "mdi:air-filter"
    accuracy_decimals: 0
    state_class: measurement
    device_class: aqi
    id: pm_2_5_aqi

switch:
# FOR TPUCH 
  - platform: template
    name: "Single"
    icon: mdi:gesture-double-tap
    id: "single_switch"
    optimistic: true

  - platform: template
    name: "Double"
    icon: mdi:gesture-double-tap
    id: "double_switch"
    optimistic: true

  - platform: template
    name: "Hold"
    icon: mdi:gesture-double-tap
    id: "hold_switch"
    optimistic: true

# LED SLEEP MODE SWITCH
  - platform: template
    name: "LED Sleep Mode"
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:sleep
    id: sleepmode
    optimistic: true

# CO2 LED SWITCH         
  - platform: gpio
    pin: 4
    id: co2led
    internal: true
# TVOC LED SWITCH     
  - platform: gpio
    pin: 32
    id: tvocch2oled
    internal: true
# PM2.5 LED SWITCH     
  - platform: gpio
    pin: 33
    id: pm25led
    internal: true

  - platform: gpio
    pin: 25
    id: button_led
    internal: true

# # WIFI STATE LED 
# status_led:
#   pin: 25

number:
# THRESHOLD CH2O
  - platform: template
    name: "Threshold CH2O"
    entity_category: "config"
    id: ch2othreshold
    optimistic: true
    unit_of_measurement: "ppb"
    min_value: 0
    max_value: 2000
    step: 10
    initial_value: 500
    restore_value: true
    icon: "mdi:led-on"
# THRESHOLD CO2
  - platform: template
    name: "Threshold CO2"
    entity_category: "config"
    id: co2threshold
    optimistic: true
    unit_of_measurement: "ppm"
    min_value: 400
    max_value: 3000
    step: 100
    initial_value: 1000
    restore_value: true
    icon: "mdi:led-on"
# THRESHOLD PM2.5    
  - platform: template
    name: "Threshold PM2.5"
    entity_category: "config"
    id: pm25threshold
    optimistic: true
    unit_of_measurement: "µg/m³"
    min_value: 0
    max_value: 200
    step: 10
    initial_value: 50
    restore_value: true
    icon: "mdi:led-on"
# THRESHOLD TVOC    
  - platform: template
    name: "Threshold TVOC"
    entity_category: "config"
    id: tvocthreshold
    optimistic: true
    unit_of_measurement: "ppb"
    min_value: 0
    max_value: 10000
    step: 100
    initial_value: 500
    restore_value: true
    icon: "mdi:led-on"
# TVOC OFFSET
  - platform: template
    name: "TVOC Offset"
    entity_category: "config"
    unit_of_measurement: "ppb"
    id: tvoc_offset_ui
    optimistic: true
    min_value: -500
    max_value: 500
    step: 1
    mode: box
    initial_value: 0
    restore_value: true
    icon: "mdi:radiator"
# TEMPERATURE OFFSET
  - platform: template
    name: "Temperature Offset"
    id: temperature_offset_ui
    unit_of_measurement: "°C"
    min_value: -20
    max_value: 20
    step: 0.1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:thermometer"
    entity_category: config
# HUMIDITY OFFSET    
  - platform: template
    name: "Humidity Offset"
    id: humidity_offset_ui
    unit_of_measurement: "%"
    min_value: -50
    max_value: 50
    step: 0.1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:water-percent"
    entity_category: config  

binary_sensor:
  - platform: gpio
    internal: true
    name: Rojo
    id: rojo
    pin: 
      number: 5
      mode: INPUT_PULLDOWN
    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 400ms
        then:
          - switch.turn_on: button_led
          - switch.turn_on: single_switch
          - delay: 500ms
          - switch.turn_off: single_switch
          - switch.turn_off: button_led
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 400ms
          - ON for 40ms to 400ms
          - OFF for at least 400ms
        then:
          - switch.turn_on: button_led
          - switch.turn_on: double_switch
          - delay: 500ms
          - switch.turn_off: double_switch
          - switch.turn_off: button_led
      - timing:
          - ON for at least 500ms
          - OFF for at least 40ms
        then:
          - switch.turn_on: button_led
          - switch.turn_on: hold_switch
          - delay: 500ms
          - switch.turn_off: hold_switch
          - switch.turn_off: button_led

  - platform: template
    internal: true
    id: tvocch2olambda
    lambda: |-
      if (id(sleepmode).state == false) {
        if (id(tvocsensor).state > id(tvocthreshold).state) {
          return true;
        } else {
          return false;
      }
      } else {
        return false;
      }
    on_press:
      then:
        - switch.turn_on: tvocch2oled
    on_release:
      then:
        - switch.turn_off: tvocch2oled

  - platform: template
    internal: true
    id: co2lambda
    lambda: |-
      if (id(sleepmode).state == false) {
        if (id(co2sensor).state > id(co2threshold).state) {
          return true;
        } else {
          return false;
      }
      } else {
        return false;
      }
    on_press:
      then:
        - switch.turn_on: co2led
    on_release:
      then:
        - switch.turn_off: co2led
  - platform: template
    internal: true
    id: pm25lambda
    lambda: |-
      if (id(sleepmode).state == false) {
        if (id(pm25sensor).state > id(pm25threshold).state) {
          return true;
        } else {
          return false;
      }
      } else {
        return false;
      }
    on_press:
      then:
        - switch.turn_on: pm25led
    on_release:
      then:
        - switch.turn_off: pm25led

  - platform: gpio
    # pin: 34
    id: rest_button
    name: "REST"
    pin: 
      number: 34
      inverted: true
      # mode: INPUT_PULLDOWN    
    internal: true
    filters:
      - delayed_on: 5ms
      - delayed_off: 5ms
    on_multi_click:
      - timing:
          - ON for at least 10s
          - OFF for at least 40ms
        then:
          - logger.log: " 長按:10 秒以上放開"
          - button.press: restart_button
          - button.press: default_mode

      - timing:
          - ON for at least 5s
          - OFF for at least 40ms
        then:
          - logger.log: " 長按:5~9 秒放開"
          - button.press: restart_button

    # 所有未符合上述 timing 的，都會落到這裡
    on_click:
      then:
        - logger.log: " 其他情況校正Co2"
        - button.press: co2sensor_zero


button:
  - platform: restart
    id: restart_button
    name: "Restart"
  - platform: factory_reset
    id: reset_all
    name: "Restart with Factory Default Settings"
    internal: true

  - platform: template
    name: "CO2 Calibration" #按下后会将当前环境CO2浓度设置为基准400ppm，按下时请确保放入室外或此时CO2浓度足够低
    icon: mdi:restart
    entity_category: "diagnostic"
    id: co2sensor_zero
    on_press:
      then:
        - logger.log: "開始進行CO2, 要進行校準 CM1106 感測器必須在穩定的 400ppm CO₂ 環境中運作至少 20 分鐘，然後才能執行此功能。"
        - cm1106.calibrate_zero: co2sensor_cm1106      

  - platform: template
    name: "Default Setting"
    id: default_mode  
    icon: "mdi:restart"   
    entity_category: config
    on_press:
      then:
        # THRESHOLD DEFAULT
        - logger.log: "Default Mode On Press"    
        - switch.turn_off: sleepmode
        - logger.log: "co2 threshold 1000"    
        - number.set:
            id: co2threshold
            value: 1000
        - logger.log: "pm25 threshold 1000"              
        - number.set:
            id: pm25threshold
            value: 50
        - logger.log: "tvoc threshold 500"              
        - number.set:
            id: tvocthreshold
            value: 500
        - logger.log: "ch2o threshold 500"     
        - number.set:
            id: ch2othreshold
            value: 500                        
        # OFFSET DEFAULT
        - logger.log: "tvoc offset 0"                  
        - number.set:
            id: tvoc_offset_ui
            value: 0
        - logger.log: "temperature_offset 0"                  
        - number.set:
            id: temperature_offset_ui
            value: 0  
        - logger.log: "humidity_offset 0"                  
        - number.set:
            id: humidity_offset_ui
            value: 0                                   

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"      
      icon: "mdi:ip-outline"
    ssid:
      name: "SSID"
      icon: "mdi:router-wireless"
    mac_address:
      name: "MAC"
      icon: "mdi:lan"
  - platform: version
    name: "Firmware"   
  - platform: template
    name: "AQI description"
    icon: "mdi:air-filter"
    id: aqi_text
  - platform: template
    name: "AQI color"
    icon: "mdi:air-filter"
    id: aqi_color
