blueprint:
  name: ED-29 Energy to ESPHome 2.9inch Display
  description: Map Home Assistant energy/cost entities to ESPHome number entities for ED-29 display
  domain: automation
  input:
    source_total_energy:
      name: Source - Total Energy Use
      selector:
        entity: {}

    esphome_total_energy:
      name: ESPHome - Total Energy Ues
      selector:
        entity:
          domain: number
          integration: esphome

    source_total_cost:
      name: Source - Total  Energy Cost
      selector:
        entity: {}

    esphome_total_cost:
      name: ESPHome - Total  Energy Cost
      selector:
        entity:
          domain: number
          integration: esphome

    source_yesterday_energy:
      name: Source - Yesterday Energy Use
      selector:
        entity: {}

    esphome_yesterday_energy:
      name: ESPHome - Yesterday Energy Use
      selector:
        entity:
          domain: number
          integration: esphome

    source_yesterday_cost:
      name: Source - Yesterday Energy Cost
      selector:
        entity: {}

    esphome_yesterday_cost:
      name: ESPHome - Yesterday Energy Cost
      selector:
        entity:
          domain: number
          integration: esphome

    source_today_energy:
      name: Source - Today Energy Use
      selector:
        entity: {}

    esphome_today_energy:
      name: ESPHome - Today Energy Use
      selector:
        entity:
          domain: number
          integration: esphome

    source_today_cost:
      name: Source - Today Energy Cost
      selector:
        entity: {}

    esphome_today_cost:
      name: ESPHome - Today Energy Cost
      selector:
        entity:
          domain: number
          integration: esphome

    source_count_kwh_cost:
      name: Source - Count kWh Cost
      selector:
        entity: {}

    esphome_count_kwh_cost:
      name: ESPHome - Count kWh Cost
      selector:
        entity:
          domain: number
          integration: esphome

    source_realtime_hour_cost:
      name: Source - Realtime Hour Cost
      selector:
        entity: {}

    esphome_realtime_hour_cost:
      name: ESPHome - Realtime Hour Cost
      selector:
        entity:
          domain: number
          integration: esphome

trigger:
  - platform: state
    entity_id:
      - !input source_total_energy
      - !input source_total_cost
      - !input source_yesterday_energy
      - !input source_yesterday_cost
      - !input source_today_energy
      - !input source_today_cost
      - !input source_count_kwh_cost
      - !input source_realtime_hour_cost
  - platform: homeassistant
    event: start

variables:
  source_total_energy: !input source_total_energy
  source_total_cost: !input source_total_cost
  source_yesterday_energy: !input source_yesterday_energy
  source_yesterday_cost: !input source_yesterday_cost
  source_today_energy: !input source_today_energy
  source_today_cost: !input source_today_cost
  source_count_kwh_cost: !input source_count_kwh_cost
  source_realtime_hour_cost: !input source_realtime_hour_cost

action:
  # Total Energy
  - service: number.set_value
    target:
      entity_id: !input esphome_total_energy
    data:
      value: "{{ states(source_total_energy) | float(-999999) | round(2)}}"

  # Total Cost
  - service: number.set_value
    target:
      entity_id: !input esphome_total_cost
    data:
      value: "{{ states(source_total_cost) | float(-999999) | round(2)}}"

  # Yesterday Energy
  - service: number.set_value
    target:
      entity_id: !input esphome_yesterday_energy
    data:
      value: "{{ states(source_yesterday_energy) | float(-999999)| round(2)}}"

  # Yesterday Cost
  - service: number.set_value
    target:
      entity_id: !input esphome_yesterday_cost
    data:
      value: "{{ states(source_yesterday_cost) | float(-999999)| round(2) }}"

  # Today Energy
  - service: number.set_value
    target:
      entity_id: !input esphome_today_energy
    data:
      value: "{{ states(source_today_energy) | float(-999999) | round(2)}}"

  # Today Cost
  - service: number.set_value
    target:
      entity_id: !input esphome_today_cost
    data:
      value: "{{ states(source_today_cost) | float(-999999) | round(2)}}"

  # Count kWh Cost
  - service: number.set_value
    target:
      entity_id: !input esphome_count_kwh_cost
    data:
      value: "{{ states(source_count_kwh_cost) | float(-999999)| round(2) }}"

  # Realtime Hour Cost
  - service: number.set_value
    target:
      entity_id: !input esphome_realtime_hour_cost
    data:
      value: "{{ states(source_realtime_hour_cost) | float(-999999) | round(2)}}"

mode: single
