blueprint:
  name: ED-29 Energy → ESPHome 2.9" Display (Dynamic Mapping)
  description: >
    將 Home Assistant 電力／費用感測資料同步到 ESPHome 數字實體（number.*），
    用於 ED-29 電子紙顯示即時更新。支援今日、昨日、總用電量與費用等項目。
  domain: automation
  author: 比爾
  source_url: https://github.com/billdev-tw/ha-blueprints/blob/main/ed29_esphome_energy_sync.yaml

  input:
    source_today_energy:
      name: Source - Today Energy Use
      selector:
        entity: {}
      default: ""
    esphome_today_energy:
      name: ESPHome - Today Energy Use
      selector:
        entity:
          domain: number
          integration: esphome
      default: ""

    source_today_cost:
      name: Source - Today Energy Cost
      selector:
        entity: {}
      default: ""
    esphome_today_cost:
      name: ESPHome - Today Energy Cost
      selector:
        entity:
          domain: number
          integration: esphome
      default: ""

    source_yesterday_energy:
      name: Source - Yesterday Energy Use
      selector:
        entity: {}
      default: ""
    esphome_yesterday_energy:
      name: ESPHome - Yesterday Energy Use
      selector:
        entity:
          domain: number
          integration: esphome
      default: ""

    source_yesterday_cost:
      name: Source - Yesterday Energy Cost
      selector:
        entity: {}
      default: ""
    esphome_yesterday_cost:
      name: ESPHome - Yesterday Energy Cost
      selector:
        entity:
          domain: number
          integration: esphome
      default: ""

    source_total_energy:
      name: Source - Total Energy Use
      selector:
        entity: {}
      default: ""
    esphome_total_energy:
      name: ESPHome - Total Energy Use
      selector:
        entity:
          domain: number
          integration: esphome
      default: ""

    source_total_cost:
      name: Source - Total Energy Cost
      selector:
        entity: {}
      default: ""
    esphome_total_cost:
      name: ESPHome - Total Energy Cost
      selector:
        entity:
          domain: number
          integration: esphome
      default: ""

    source_count_kwh_cost:
      name: Source - Count kWh Cost
      selector:
        entity: {}
      default: ""
    esphome_count_kwh_cost:
      name: ESPHome - Count kWh Cost
      selector:
        entity:
          domain: number
          integration: esphome
      default: ""

    source_realtime_hour_cost:
      name: Source - Realtime Hour Cost
      selector:
        entity: {}
      default: ""
    esphome_realtime_hour_cost:
      name: ESPHome - Realtime Hour Cost
      selector:
        entity:
          domain: number
          integration: esphome
      default: ""

trigger:
  - platform: state
    entity_id:
      - !input source_today_energy
      - !input source_today_cost
      - !input source_yesterday_energy
      - !input source_yesterday_cost
      - !input source_total_energy
      - !input source_total_cost
      - !input source_count_kwh_cost
      - !input source_realtime_hour_cost
    for: "00:00:01"
  - platform: homeassistant
    event: start

variables:
  mappings:
    - source: !input source_today_energy
      target: !input esphome_today_energy
    - source: !input source_today_cost
      target: !input esphome_today_cost
    - source: !input source_yesterday_energy
      target: !input esphome_yesterday_energy
    - source: !input source_yesterday_cost
      target: !input esphome_yesterday_cost
    - source: !input source_total_energy
      target: !input esphome_total_energy
    - source: !input source_total_cost
      target: !input esphome_total_cost
    - source: !input source_count_kwh_cost
      target: !input esphome_count_kwh_cost
    - source: !input source_realtime_hour_cost
      target: !input esphome_realtime_hour_cost

action:
  - repeat:
      for_each: "{{ mappings }}"
      sequence:
        - if:
            - condition: template
              value_template: "{{ repeat.item.source != '' and repeat.item.target != '' }}"
          then:
            - service: number.set_value
              target:
                entity_id: "{{ repeat.item.target }}"
              data:
                value: >-
                  {% set v = states(repeat.item.source) | float(none) %}
                  {% if v is number %}
                    {{ v | round(2) }}
                  {% else %}
                    {{ states(repeat.item.target) | float }}
                  {% endif %}

mode: restart


# blueprint:
#   name: ED-29 Energy to ESPHome 2.9inch Display (Dynamic Mapping)
#   description: Map Home Assistant energy/cost entities to ESPHome number entities for ED-29 display (optional inputs supported)
#   domain: automation
#   input:
#     source_today_energy:
#       name: Source - Today Energy Use
#       selector:
#         entity: {}
#       default: ""
#     esphome_today_energy:
#       name: ED-29 ESPHome - Today Energy Use
#       selector:
#         entity:
#           domain: number
#           integration: esphome
#       default: ""

#     source_today_cost:
#       name: Source - Today Energy Cost
#       selector:
#         entity: {}
#       default: ""
#     esphome_today_cost:
#       name: ED-29 ESPHome - Today Energy Cost
#       selector:
#         entity:
#           domain: number
#           integration: esphome
#       default: ""


#     source_yesterday_energy:
#       name: Source - Yesterday Energy Use
#       selector:
#         entity: {}
#       default: ""
#     esphome_yesterday_energy:
#       name: ED-29 ESPHome - Yesterday Energy Use
#       selector:
#         entity:
#           domain: number
#           integration: esphome
#       default: ""

#     source_yesterday_cost:
#       name: Source - Yesterday Energy Cost
#       selector:
#         entity: {}
#       default: ""
#     esphome_yesterday_cost:
#       name: ED-29 ESPHome - Yesterday Energy Cost
#       selector:
#         entity:
#           domain: number
#           integration: esphome
#       default: ""      
#     source_total_energy:
#       name: Source - Total Energy Use
#       selector:
#         entity: {}
#       default: ""
#     esphome_total_energy:
#       name: ED-29 ESPHome - Total Energy Use
#       selector:
#         entity:
#           domain: number
#           integration: esphome
#       default: ""

#     source_total_cost:
#       name: Source - Total Energy Cost
#       selector:
#         entity: {}
#       default: ""
#     esphome_total_cost:
#       name: ED-29 ESPHome - Total Energy Cost
#       selector:
#         entity:
#           domain: number
#           integration: esphome
#       default: ""

#     source_count_kwh_cost:
#       name: Source - Count kWh Cost
#       selector:
#         entity: {}
#       default: ""
#     esphome_count_kwh_cost:
#       name: ED-29 ESPHome - Count kWh Cost
#       selector:
#         entity:
#           domain: number
#           integration: esphome
#       default: ""

#     source_realtime_hour_cost:
#       name: Source - Realtime Hour Cost
#       selector:
#         entity: {}
#       default: ""
#     esphome_realtime_hour_cost:
#       name: ED-29 ESPHome - Realtime Hour Cost
#       selector:
#         entity:
#           domain: number
#           integration: esphome
#       default: ""

# trigger:
#   - platform: state
#     entity_id:
#       - !input source_total_energy
#       - !input source_total_cost
#       - !input source_yesterday_energy
#       - !input source_yesterday_cost
#       - !input source_today_energy
#       - !input source_today_cost
#       - !input source_count_kwh_cost
#       - !input source_realtime_hour_cost
#     for: "00:00:01"
#   - platform: homeassistant
#     event: start

# variables:
#   mappings:
#     - source: !input source_total_energy
#       target: !input esphome_total_energy
#     - source: !input source_total_cost
#       target: !input esphome_total_cost
#     - source: !input source_yesterday_energy
#       target: !input esphome_yesterday_energy
#     - source: !input source_yesterday_cost
#       target: !input esphome_yesterday_cost
#     - source: !input source_today_energy
#       target: !input esphome_today_energy
#     - source: !input source_today_cost
#       target: !input esphome_today_cost
#     - source: !input source_count_kwh_cost
#       target: !input esphome_count_kwh_cost
#     - source: !input source_realtime_hour_cost
#       target: !input esphome_realtime_hour_cost

# action:
#   - repeat:
#       for_each: "{{ mappings }}"
#       sequence:
#         - if:
#             - condition: template
#               value_template: "{{ repeat.item.source != '' and repeat.item.target != '' }}"
#           then:
#             - service: number.set_value
#               target:
#                 entity_id: "{{ repeat.item.target }}"
#               data:
#                 value: "{{ states(repeat.item.source) | float(-999999) | round(2) }}"

# mode: single
