blueprint:
  name: ED-29 Forecast to ESPHome 2.9inch Display
  description: Map Home Assistant forecast entities to ESPHome entities for ED-29 display (supports number & text domains)
  domain: automation
  input:
    source_feels_like_temperature:
      name: Source - Feels Like Temperature
      selector:
        entity: {}
      default: ""
    esphome_feels_like_temperature:
      name: ESPHome - Feels Like Temperature
      selector:
        entity:
          domain: number
          integration: esphome
      default: ""

    source_weather_condition:
      name: Source - Weather Condition
      selector:
        entity: {}
      default: ""
    esphome_weather_condition:
      name: ESPHome - Weather Condition
      selector:
        entity:
          domain: text
          integration: esphome
      default: ""

    source_weather_tw_condition:
      name: Source - Weather TW Condition
      selector:
        entity: {}
      default: ""
    esphome_weather_tw_condition:
      name: ESPHome - Weather TW Condition
      selector:
        entity:
          domain: text
          integration: esphome
      default: ""

trigger:
  - platform: state
    entity_id:
      - !input source_feels_like_temperature
      - !input source_weather_condition
      - !input source_weather_tw_condition
    for: "00:00:01"

  - platform: homeassistant
    event: start

  # 每 10 分鐘觸發一次
  - platform: time_pattern
    minutes: "/10"

variables:
  mappings:
    - source: !input source_feels_like_temperature
      target: !input esphome_feels_like_temperature
    - source: !input source_weather_condition
      target: !input esphome_weather_condition
    - source: !input source_weather_tw_condition
      target: !input esphome_weather_tw_condition

action:
  - repeat:
      for_each: "{{ mappings }}"
      sequence:
        - if:
            - condition: template
              value_template: "{{ repeat.item.source != '' and repeat.item.target != '' }}"
          then:
            - choose:
                # 如果目標是 number
                - conditions:
                    - condition: template
                      value_template: "{{ repeat.item.target.startswith('number.') }}"
                  sequence:
                    - service: number.set_value
                      target:
                        entity_id: "{{ repeat.item.target }}"
                      data:
                        value: "{{ states(repeat.item.source) | float(-999999) | round(2) }}"

                # 如果目標是 text
                - conditions:
                    - condition: template
                      value_template: "{{ repeat.item.target.startswith('text.') }}"
                  sequence:
                    - service: text.set_value
                      target:
                        entity_id: "{{ repeat.item.target }}"
                      data:
                        value: "{{ states(repeat.item.source) | string }}"

mode: single
