blueprint:
  name: ED-29 Energy to ESPHome 2.9inch Display  
  description: Select ANY entity and display on ESPHome device (ESPHome only)
  domain: automation
  input:
    source_entity:
      name: Entity to Display
      description: Choose ANY entity from your Home Assistant
      selector:
        entity: {}

    # esphome_device:  # 目前還不支持動態連結
    #   name: ESPHome Device
    #   description: Select your ESPHome device
    #   selector:
    #     device:
    #       integration: esphome

    esphome_number:
      name: ESPHome Display Number
      description: Select the number entity from the chosen ESPHome device
      selector:
        entity:
          domain: number
          integration: esphome
trigger:
  - platform: state
    entity_id: !input source_entity
  - platform: homeassistant
    event: start
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.platform == 'homeassistant' }}"
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
action:
  - variables:
      source_entity: !input source_entity
  - service: number.set_value
    target:
      entity_id: !input esphome_number
    data:
      value: "{{ states(source_entity) | float(-999999) }}"
mode: single
          
