esphome:
  name: pm02
  friendly_name: pm02

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
    
api:
  reboot_timeout: 0s

web_server:
  port: 80
  version: 3

ota:
  - platform: esphome
    id: ota_esphome
  - platform: web_server
    id: web_server_managed  


ethernet:
  type: W5500
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12
  cs_pin: GPIO15
  interrupt_pin: GPIO4

    
