

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    name: Binary Sensor_1
    pin:
      number: P28
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - if:
            condition:    
              lambda: 'return !id(decouple_1).state;'
            then: 
              - fan.toggle: bedroom_fan
fan:
  - platform: binary
    name: "Bedroom Fan"
    icon: "mdi:fan"
    output: switch_1
    id: bedroom_fan

output:
  - platform: gpio
    pin: P16
    id: switch_1
    
switch:
  - platform: template
    name: "decouple relay_1"
    id: decouple_1
    icon: mdi:link-variant
    optimistic: true
    entity_category: config
    on_turn_on:
      then:
      - switch.turn_on: decouple_1
    on_turn_off:
      then:
      - switch.turn_off: decouple_1  
