esphome:
  name: "wall-switch-1-cbu-XXXXXX" # 後6碼一定要跟自家的設備後碼一致
  friendly_name: wall-switch-1-cbu-XXXXXX  # 可自定辨識度高的英文

bk72xx:
  board: cbu

# Enable logging
logger:

# Enable Home Assistant API
api:

#2024/06/29 Update For ESPHome 6 或以上適用
ota:
 - platform: esphome

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

captive_portal:

web_server:
  port: 80  

button:
  - platform: restart
    name: Restart    

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"      
      icon: "mdi:ip-outline"
    mac_address:
      name: "MAC"
      icon: "mdi:lan"
    ssid:
      name: SSID      

sensor:
  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 600s  

binary_sensor:
  - platform: gpio
    id: binary_sensor_1
    name: "binary_sensor_1"
    pin:
      number: 16
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - if:
            condition:    
              lambda: 'return !id(decouple_1).state;'
            then: 
              - switch.toggle: relay_1
switch:
  - platform: gpio
    id: relay_1
    name: "realy_1"
    pin: 24
  - platform: template
    name: "decouple_relay_1"
    id: decouple_1
    icon: mdi:link-variant
    optimistic: true
    entity_category: config
    on_turn_on:
      then:
      - switch.turn_on: decouple_1
    on_turn_off:
      then:
      - switch.turn_off: decouple_1  

output:
  - platform: gpio
    pin: 17
    id: gpio_led

light:
  - platform: binary
    output: gpio_led
    id: lightid    
