esphome:
  name: wall-switch-2
  friendly_name: Wall Switch 2

bk72xx:
  board: cbu

logger:

web_server:

captive_portal:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "wall-switch-2-0001"
    password: ""
    
button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"      
      icon: "mdi:ip-outline"
    mac_address:
      name: "MAC"
      icon: "mdi:lan"
    ssid:
      name: SSID      

sensor:
  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 600s    

switch:
  - platform: gpio
    id: relay_1
    name: "relay_1"
    pin: 22
  - platform: gpio
    id: relay_2
    name: "relay_2"
    pin: 26    

  - platform: template
    name: "decouple_relay_1"
    id: decouple_1
    icon: mdi:link-variant
    optimistic: true
    entity_category: config
    on_turn_on:
      then:
      - switch.turn_on: decouple_1
    on_turn_off:
      then:
      - switch.turn_off: decouple_1  

  - platform: template
    name: "decouple_relay_2"
    id: decouple_2
    icon: mdi:link-variant
    optimistic: true
    entity_category: config
    on_turn_on:
      then:
      - switch.turn_on: decouple_2
    on_turn_off:
      then:
      - switch.turn_off: decouple_2        

binary_sensor:
  - platform: gpio
    id: binary_sensor_1
    name: "binary_sensor_1"
    pin:
      number: 14
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - if:
            condition:    
              lambda: 'return !id(decouple_1).state;'
            then: 
              - switch.toggle: relay_1

  - platform: gpio
    id: binary_sensor_2
    name: "binary_sensor_2"
    pin:
      number: 15
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - if:
            condition:    
              lambda: 'return !id(decouple_2).state;'
            then: 
              - switch.toggle: relay_2
output:
  - platform: gpio
    pin: 17
    id: gpio_led

light:
  - platform: binary
    output: gpio_led
    id: lightid
