esphome:
  name: "automate-ed-29"
  friendly_name: AUTOMATE ED-29
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password  
  ap: {}

web_server:
  port: 80

captive_portal:
  
font:
  - file: 'fonts/SFProDisplay-Medium.ttf'  # 純英文字
    id: my_font #yes
    size: 26
    glyphs: 
      ['+!,."%-_:°/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz ']  

  - file: 'fonts/NotoSansTC-Light.ttf'   #中文字
    id: font_tw
    size: 30
    glyphs: 
     ['歐特美字數多']

  - file: 'fonts/GenJyuuGothic-Medium.ttf'
    id: font_tw_a
    size: 30     
    glyphs: 
     ['歐特美圓體字']
spi:
  clk_pin: D5
  mosi_pin: D7

display:
  - platform: waveshare_epaper
    id: my_display
    cs_pin: D8
    dc_pin: D2
    busy_pin: D1
    reset_pin: D4
    model: 2.90in
    full_update_every: 60
    rotation: 270°
    lambda: |-
      it.print(0, 0, id(my_font), "AUTOMATE ED-29");  
      it.print(0, 30, id(my_font), "2.9inch ePaper");  
      it.print(0, 60, id(font_tw), "歐特美字數多");  
      it.print(0, 90, id(font_tw_a), "歐特美圓體字");  
